//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroceryStoreApp.Databases
{
    using System;
    using System.Collections.Generic;
    
    public partial class Адрес
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Адрес()
        {
            this.МестоОтправки = new HashSet<МестоОтправки>();
            this.Филиал = new HashSet<Филиал>();
        }
    
        public int Код { get; set; }
        public int Регион { get; set; }
        public int НаселённыйПункт { get; set; }
        public int Улица { get; set; }
        public short Дом { get; set; }
        public bool ТипАдреса { get; set; }
    
        public virtual НаселённыйПункт НаселённыйПункт1 { get; set; }
        public virtual Регион Регион1 { get; set; }
        public virtual Улица Улица1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<МестоОтправки> МестоОтправки { get; set; }
        public virtual Сотрудник Сотрудник { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Филиал> Филиал { get; set; }
    }
}
