//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroceryStoreApp.Databases
{
    using System;
    using System.Collections.Generic;
    
    public partial class Поставка
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Поставка()
        {
            this.ТоварПоставка = new HashSet<ТоварПоставка>();
        }
    
        public int Код { get; set; }
        public Nullable<int> КодМестаОтправки { get; set; }
        public Nullable<int> КодФилиала { get; set; }
        public System.DateTime ДатаЗаявки { get; set; }
        public System.DateTime ДатаПоставки { get; set; }
    
        public virtual МестоОтправки МестоОтправки { get; set; }
        public virtual Филиал Филиал { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ТоварПоставка> ТоварПоставка { get; set; }
    }
}
